config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'blogger#index'

  get '/places/:id', to: 'places#show', as: 'place'

  resources :blogs
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
    can :manage, :all
    else
    can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :tourist
  belongs_to :place
  has_many :pictures


end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :blog
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :blogs
  has_many :tourists, through: :blogs
end

app/models/tourist.rb
class Tourist < ActiveRecord::Base
  has_many :blogs
  has_many :places, through: :blogs
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role
  end
  
end

app/controllers/blogger_controller.rb
class BloggerController < ApplicationController
  
  def index
  	@places = Place.take(3)
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  load_and_authorize_resource
	def index

	end
	
	# GET new_blog_url
    def new
      # return an HTML form for describing the new blog
    end

    # POST blog_url
    def create
      # create an blog
      params[:blog][:published_on] = Date.today
      params[:blog][:tags] = ["Manali", "Couple", "Honeymoon", "Flight", "March"]

      @blog = Blog.new(params.require(:blog).permit(:tourist_id, :place_id, :title, :body, :published_on, :tags))

      @blog.save
      redirect_to @blog
      #render plain: params[:blog].inspect
    end

    # GET blog_url
    def show
      # find and return the blog
    #  @blog = Blog.find(params[:id])
      logger.debug @blog.title
    end

    # GET edit_blog_url
    def edit
      # return an HTML form for editing the blog
    end

    # PUT blog_url
    def update
      # find and update the blog
    end

    # DELETE blog_url
    def destroy
      # delete the blog
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	load_and_authorize_resource
	def show
	#	@place = Place.find(params[:id])
		@blogs = @place.blogs.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogger_helper.rb
module BloggerHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/blogger/index.html.erb
<h1>My Tripsy</h1>
<p> Top 3 trending hot-spots</p>
<% @places.each do |place| %>
    <p><%= link_to place.name, place_path(place.id) %></p>
<% end %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @blog.text %>
</p>

app/views/blogs/new.html.erb
<h1> New Blog </h1>
<% if can? :create, Blog %>
  <%= form_for :blog, url: blogs_path do |f| %>
    <p>
      <%= f.label :tourist_id %><br>
      <%= f.text_field :tourist_id %>
    </p>

    <p>
      <%= f.label :place_id %><br>
      <%= f.text_field :place_id %>
    </p>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.label :tags %><br>
      <%= f.text_field :tags %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

app/views/blogs/show.html.erb
<h1>Blogs</h1>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @blog.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<p>Codeship trial</p>
	<div id="user_nav">
	  <% if user_signed_in? %>
	    Signed in as <%= current_user.email %>. Not you?
	    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>
	    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>
	</div>
	<%= yield %>
</body>
</html>

app/views/places/show.html.erb
<h1>Place: <%= @place.name.titleize %></h1>
<p> State: <%= @place.state.titleize %></p>
<p> Best season to visit: <%= @place.best_season.to_sentence %></p>
<p> Coordinates : <%= @place.coordinate.upcase %></p>

<% if can? :create, Blog %>
  <%= link_to 'Write a Blog', new_blog_path %>
<% end %>


<% @blogs.each do |b| %>
    <p><%= link_to b.title, blog_path(b.id) %></p>
<% end %>